In [1]:
#!pip install -q datasets

In [2]:
from datasets import load_dataset

In [3]:
dados_redacoes = load_dataset('csv', data_files='/content/redacoes.csv',)

Generating train split: 0 examples [00:00, ? examples/s]

In [4]:
dados_redacoes

DatasetDict({
    train: Dataset({
        features: ['essay', 'score'],
        num_rows: 4570
    })
})

## Pelo fato da base de dados ser pequena, isso invabiliza utiliza-la para treinar o nosso modelo. Então vamos utilizar uma técnica chamada de Transferência de aprendizado, onde recuperamos o aprendizado de um modelo que foi treinado com uma grande base de dados e transferimos ao nosso modelo

In [5]:
dados_redacoes['train'].features

{'essay': Value('string'), 'score': Value('int64')}

In [6]:
dados_redacoes['train']['essay'][0]

'A convivência com o ensino em uma escola pública , nos mostra \\xa0como a reforma do ensino médio é necessária, com o ensino precário, escolas quase desabando, falta de educadores,a formação de estudantes fica a \\xa0cada dia mais difícil., Atualmente o índice de jovens que procuram uma educação de qualidade é maior do que em todos os séculos , temos em vista que todos procuram a melhoria, tanto na estrutura da instituição como no ensino, muitos sonham em ser: médicos, professores,advogados, contadores, e assim sucessivamente., A solução seria a constatação de uma lei em prol dos estudantes, precisamos ser ouvidos, a voz dos jovens é a voz do futuro, queremos o ensino superior, queremos oportunidades em escolas públicas, escolas bem estruturada e profissionais competentes., Creio \\xa0que a reforma deveria ocorrer, pois o intuito é a melhoria (Que tipo de melhoria?,\\xa0assim todos os jovens teriam a oportunidade de serem profissionais de sucesso. O incentivo ( aos jovens é o que torna o país como sendo uma pátria de governantes justos e conhecedores de seus deveres .'

In [7]:
dados_redacoes['train']['score'][0]

4

In [8]:
dados_redacoes['train'].to_pandas()

                                                  essay  score
0     A convivência com o ensino em uma escola públi...      4
1     O Brasil possui aproximadamente 425 mil polici...      5
2     O esporte é muito importante, as Olimpíadas, u...      8
3     O conceito de "banalidade do mal" da filósofa ...      8
4     Um dos assuntos que mais geram discussões atua...      5
...                                                 ...    ...
4565  Com o início da era digital, a capacidade de t...      6
4566  O feminicídio é o assassinato de uma mulher, a...      4
4567  Foram vrias as conquistas que as mulheres bras...      5
4568  Segundo o psicoterapeuta Ivan Carpelatto: “a v...      9
4569  Promulgada em 1988, a Constituição Federal a e...      7

[4570 rows x 2 columns]

In [9]:
treino_teste = dados_redacoes['train'].train_test_split(test_size = 0.2, shuffle = False)
treino_teste

DatasetDict({
    train: Dataset({
        features: ['essay', 'score'],
        num_rows: 3656
    })
    test: Dataset({
        features: ['essay', 'score'],
        num_rows: 914
    })
})

In [10]:
from datasets import DatasetDict

In [11]:
dados_redacoes = DatasetDict({
    'treino': treino_teste['train'],
    'teste': treino_teste['test']
})

In [12]:
dados_redacoes

DatasetDict({
    treino: Dataset({
        features: ['essay', 'score'],
        num_rows: 3656
    })
    teste: Dataset({
        features: ['essay', 'score'],
        num_rows: 914
    })
})

In [13]:
checkpoint_modelo = 'Geotrend/distilbert-base-pt-cased'

In [14]:
from transformers import AutoTokenizer

In [15]:
tokenizador = AutoTokenizer.from_pretrained(checkpoint_modelo)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/557 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

In [16]:
texto = dados_redacoes['treino']['essay'][0]

In [17]:
tokens = tokenizador.tokenize(texto)
print(tokens)

['A', 'con', '##viv', '##ência', 'com', 'o', 'ensino', 'em', 'uma', 'escola', 'pública', ',', 'nos', 'mostra', '\\', 'xa', '##0', '##com', '##o', 'a', 'reforma', 'do', 'ensino', 'médio', 'é', 'ne', '##ces', '##s', '##ária', ',', 'com', 'o', 'ensino', 'pre', '##c', '##ário', ',', 'escolas', 'quase', 'desa', '##band', '##o', ',', 'falta', 'de', 'edu', '##cado', '##res', ',', 'a', 'formação', 'de', 'estudantes', 'fica', 'a', '\\', 'xa', '##0', '##cada', 'dia', 'mais', 'difícil', '.', ',', 'Atualmente', 'o', 'índice', 'de', 'jovens', 'que', 'procura', '##m', 'uma', 'educação', 'de', 'qualidade', 'é', 'maior', 'do', 'que', 'em', 'todos', 'os', 'séculos', ',', 'tem', '##os', 'em', 'vista', 'que', 'todos', 'procura', '##m', 'a', 'melhor', '##ia', ',', 'tanto', 'na', 'estrutura', 'da', 'instituição', 'como', 'no', 'ensino', ',', 'muitos', 'son', '##ham', 'em', 'ser', ':', 'médicos', ',', 'professore', '##s', ',', 'ad', '##vog', '##ados', ',', 'conta', '##dores', ',', 'e', 'assim', 'su', '##ces', '##siva', '##mente', '.', ',', 'A', 'sol', '##ução', 'seria', 'a', 'consta', '##tação', 'de', 'uma', 'lei', 'em', 'pro', '##l', 'dos', 'estudantes', ',', 'precisa', '##mos', 'ser', 'ou', '##vidos', ',', 'a', 'voz', 'dos', 'jovens', 'é', 'a', 'voz', 'do', 'futuro', ',', 'quer', '##emos', 'o', 'ensino', 'superior', ',', 'quer', '##emos', 'oportunidades', 'em', 'escolas', 'públicas', ',', 'escolas', 'bem', 'estrutura', '##da', 'e', 'profissionais', 'compete', '##ntes', '.', ',', 'C', '##rei', '##o', '\\', 'xa', '##0', '##que', 'a', 'reforma', 'deveria', 'ocorre', '##r', ',', 'pois', 'o', 'int', '##uito', 'é', 'a', 'melhor', '##ia', '(', 'Que', 'tipo', 'de', 'melhor', '##ia', '?', ',', '\\', 'xa', '##0', '##ass', '##im', 'todos', 'os', 'jovens', 'teria', '##m', 'a', 'oportunidad', '##e', 'de', 'serem', 'profissionais', 'de', 'sucesso', '.', 'O', 'in', '##cent', '##ivo', '(', 'aos', 'jovens', 'é', 'o', 'que', 'torna', 'o', 'país', 'como', 'sendo', 'uma', 'p', '##át', '##ria', 'de', 'govern', '##antes', 'justo', '##s', 'e', 'con', '##he', '##cedo', '##res', 'de', 'seus', 'deve', '##res', '.']

In [18]:
ids = tokenizador.convert_tokens_to_ids(tokens)
print(ids)

[46, 270, 24522, 2475, 303, 91, 13849, 348, 469, 5148, 5155, 25, 1125, 4201, 73, 5308, 759, 5563, 231, 77, 8008, 246, 13849, 19640, 144, 539, 2597, 206, 4354, 25, 303, 91, 13849, 1480, 415, 2854, 25, 16687, 8774, 3151, 4948, 231, 25, 5988, 203, 5725, 8294, 920, 25, 77, 11569, 203, 22157, 13510, 77, 73, 5308, 759, 6073, 608, 578, 7859, 27, 25, 12242, 91, 20373, 203, 18423, 220, 21237, 244, 469, 17937, 203, 16944, 144, 2695, 246, 220, 348, 1692, 463, 16426, 25, 1802, 383, 348, 3416, 220, 1692, 21237, 244, 77, 5915, 359, 25, 1813, 230, 9885, 240, 21600, 314, 286, 13849, 25, 6455, 385, 1948, 348, 510, 39, 17306, 25, 17575, 206, 25, 712, 22852, 2092, 25, 5719, 2669, 25, 81, 4832, 292, 2597, 12125, 576, 27, 25, 46, 2996, 10877, 4245, 77, 10673, 15832, 203, 469, 2900, 348, 955, 258, 441, 22157, 25, 15218, 2041, 510, 465, 17157, 25, 77, 4567, 441, 18423, 144, 77, 4567, 246, 5343, 25, 15894, 16539, 91, 13849, 3121, 25, 15894, 16539, 21388, 348, 16687, 13027, 25, 16687, 4577, 9885, 317, 81, 23395, 9010, 2541, 27, 25, 48, 8439, 231, 73, 5308, 759, 899, 77, 8008, 23312, 14665, 227, 25, 4844, 91, 6857, 24540, 144, 77, 5915, 359, 21, 7080, 1911, 203, 5915, 359, 44, 25, 73, 5308, 759, 23325, 1224, 1692, 463, 18423, 13121, 244, 77, 16843, 211, 203, 14346, 23395, 203, 7505, 27, 60, 205, 6686, 2704, 21, 2255, 18423, 144, 91, 220, 6247, 91, 1425, 314, 2371, 469, 92, 1350, 797, 203, 6579, 6661, 20371, 206, 81, 270, 1168, 24814, 920, 203, 1119, 4635, 920, 27]

In [19]:
texto_decodificado = tokenizador.decode(ids)
print(texto_decodificado)

A convivência com o ensino em uma escola pública, nos mostra \ xa0como a reforma do ensino médio é necessária, com o ensino precário, escolas quase desabando, falta de educadores, a formação de estudantes fica a \ xa0cada dia mais difícil., Atualmente o índice de jovens que procuram uma educação de qualidade é maior do que em todos os séculos, temos em vista que todos procuram a melhoria, tanto na estrutura da instituição como no ensino, muitos sonham em ser : médicos, professores, advogados, contadores, e assim sucessivamente., A solução seria a constatação de uma lei em prol dos estudantes, precisamos ser ouvidos, a voz dos jovens é a voz do futuro, queremos o ensino superior, queremos oportunidades em escolas públicas, escolas bem estruturada e profissionais competentes., Creio \ xa0que a reforma deveria ocorrer, pois o intuito é a melhoria ( Que tipo de melhoria?, \ xa0assim todos os jovens teriam a oportunidade de serem profissionais de sucesso. O incentivo ( aos jovens é o que torna o país como sendo uma pátria de governantes justos e conhecedores de seus deveres.

In [20]:
import tensorflow as tf
# Alterando para 'np' (NumPy) que é amplamente compatível
input_codificado = tokenizador(texto, return_tensors = 'np')
print(input_codificado)

{'input_ids': array([[   11,    46,   270, 24522,  2475,   303,    91, 13849,   348,
          469,  5148,  5155,    25,  1125,  4201,    73,  5308,   759,
         5563,   231,    77,  8008,   246, 13849, 19640,   144,   539,
         2597,   206,  4354,    25,   303,    91, 13849,  1480,   415,
         2854,    25, 16687,  8774,  3151,  4948,   231,    25,  5988,
          203,  5725,  8294,   920,    25,    77, 11569,   203, 22157,
        13510,    77,    73,  5308,   759,  6073,   608,   578,  7859,
           27,    25, 12242,    91, 20373,   203, 18423,   220, 21237,
          244,   469, 17937,   203, 16944,   144,  2695,   246,   220,
          348,  1692,   463, 16426,    25,  1802,   383,   348,  3416,
          220,  1692, 21237,   244,    77,  5915,   359,    25,  1813,
          230,  9885,   240, 21600,   314,   286, 13849,    25,  6455,
          385,  1948,   348,   510,    39, 17306,    25, 17575,   206,
           25,   712, 22852,  2092,    25,  5719,  2669,    25,    81,
         4832,   292,  2597, 12125,   576,    27,    25,    46,  2996,
        10877,  4245,    77, 10673, 15832,   203,   469,  2900,   348,
          955,   258,   441, 22157,    25, 15218,  2041,   510,   465,
        17157,    25,    77,  4567,   441, 18423,   144,    77,  4567,
          246,  5343,    25, 15894, 16539,    91, 13849,  3121,    25,
        15894, 16539, 21388,   348, 16687, 13027,    25, 16687,  4577,
         9885,   317,    81, 23395,  9010,  2541,    27,    25,    48,
         8439,   231,    73,  5308,   759,   899,    77,  8008, 23312,
        14665,   227,    25,  4844,    91,  6857, 24540,   144,    77,
         5915,   359,    21,  7080,  1911,   203,  5915,   359,    44,
           25,    73,  5308,   759, 23325,  1224,  1692,   463, 18423,
        13121,   244,    77, 16843,   211,   203, 14346, 23395,   203,
         7505,    27,    60,   205,  6686,  2704,    21,  2255, 18423,
          144,    91,   220,  6247,    91,  1425,   314,  2371,   469,
           92,  1350,   797,   203,  6579,  6661, 20371,   206,    81,
          270,  1168, 24814,   920,   203,  1119,  4635,   920,    27,
           12]]), 'attention_mask': array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1]])}

In [21]:
def funcao_tokenizadora(dados_texto):
    return tokenizador(dados_texto['essay'], truncation = True)

In [22]:
dataset_tokenizado = dados_redacoes.map(funcao_tokenizadora, batched = True, remove_columns = ['essay'])

Map:   0%|          | 0/3656 [00:00<?, ? examples/s]

Map:   0%|          | 0/914 [00:00<?, ? examples/s]

In [23]:
dataset_tokenizado

DatasetDict({
    treino: Dataset({
        features: ['score', 'input_ids', 'attention_mask'],
        num_rows: 3656
    })
    teste: Dataset({
        features: ['score', 'input_ids', 'attention_mask'],
        num_rows: 914
    })
})

In [24]:
dataset_tokenizado['treino'].to_pandas()

,score,input_ids,attention_mask
0,4,"[11, 46, 270, 24522, 2475, 303, 91, 13849, 348...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,5,"[11, 60, 1497, 6656, 5124, 9019, 2782, 22218, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,8,"[11, 60, 290, 8465, 144, 3240, 1668, 25, 243, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,8,"[11, 60, 19131, 203, 15, 23380, 19311, 246, 28...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,5,"[11, 2567, 441, 17363, 206, 220, 578, 2989, 78...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
...,...,...,...
3651,5,"[11, 46, 5148, 1802, 469, 17870, 7326, 230, 11...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3652,6,"[11, 60, 7234, 1280, 3543, 1802, 91, 2885, 203...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3653,4,"[11, 7855, 325, 4776, 4323, 1559, 14086, 13232...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3654,6,"[11, 60, 23602, 235, 326, 23949, 206, 203, 179...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3655,8,"[11, 15, 617, 10112, 755, 91, 8987, 1071, 77, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [25]:
dataset_tokenizado['teste'].to_pandas()

,score,input_ids,attention_mask
0,7,"[11, 60, 9133, 18342, 2294, 220, 13606, 1295, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,8,"[11, 599, 3088, 1306, 25, 22568, 2284, 2251, 8...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,4,"[11, 46, 15182, 20233, 16866, 2969, 14150, 81,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,7,"[11, 60, 10910, 303, 469, 7592, 1828, 21261, 1...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,7,"[11, 1876, 91, 3222, 240, 1774, 9151, 359, 25,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
...,...,...,...
909,6,"[11, 3444, 91, 5764, 240, 452, 3543, 25, 77, 1...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
910,4,"[11, 60, 4880, 1235, 2011, 3575, 144, 91, 2370...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
911,5,"[11, 24848, 98, 8544, 243, 6634, 206, 220, 243...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
912,9,"[11, 4433, 91, 22999, 22429, 14533, 3507, 304,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
913,7,"[11, 2344, 14232, 8091, 348, 534, 25, 77, 2464...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

# Ajustando a variavel Alvo

In [26]:
dataset_tokenizado['treino'].features['score']

Value('int64')

In [27]:
from datasets import ClassLabel

In [28]:
dataset_tokenizado['treino'].unique('score')

[4, 5, 8, 6, 10, 7, 1, 9, 3, 0, 2]

In [29]:
scores = ClassLabel(names = [str(i) for i in range(11)])

In [30]:
scores

ClassLabel(names=['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])

In [31]:
def mapear_labels(dados):
    dados['label'] = scores.str2int(str(dados['score']))
    return dados

In [32]:
dataset_tokenizado = dataset_tokenizado.map(mapear_labels, remove_columns = ['score'])

Map:   0%|          | 0/3656 [00:00<?, ? examples/s]

Map:   0%|          | 0/914 [00:00<?, ? examples/s]

In [33]:
dataset_tokenizado = dataset_tokenizado.cast_column('label', scores)

Casting the dataset:   0%|          | 0/3656 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/914 [00:00<?, ? examples/s]

In [34]:
dataset_tokenizado

DatasetDict({
    treino: Dataset({
        features: ['input_ids', 'attention_mask', 'label'],
        num_rows: 3656
    })
    teste: Dataset({
        features: ['input_ids', 'attention_mask', 'label'],
        num_rows: 914
    })
})

In [35]:
dataset_tokenizado['treino'].features['label']

ClassLabel(names=['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])

## Preparação para a classificação de dados

In [36]:
from transformers import TFAutoModelForSequenceClassification

In [37]:
checkpoint_modelo = 'Geotrend/distilbert-base-pt-cased'

### Carregamento do modelo para classificação

In [38]:
id2label = {0: '0', 1: '1', 2:'2', 3:'3', 4:'4', 5:'5', 6:'6', 7:'7', 8:'8', 9:'9',10:'10'}
label2id = {valor: chave for chave, valor in id2label.items()}

modelo = TFAutoModelForSequenceClassification.from_pretrained(
    checkpoint_modelo,
    num_labels = dataset_tokenizado['treino'].features['label'].num_classes,
    id2label = id2label,
    label2id = label2id,
    from_pt = True
)

pytorch_model.bin:   0%|          | 0.00/251M [00:00<?, ?B/s]

TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.
Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFDistilBertForSequenceClassification: ['vocab_layer_norm.weight', 'vocab_layer_norm.bias', 'vocab_projector.bias', 'vocab_transform.bias', 'vocab_transform.weight', 'vocab_projector.weight']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
Some weights or buffers of the TF 2.0 model TFDistilBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['pre_classifier.weight', 'pre_classifier.bias', 'classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [39]:
from transformers import DataCollatorWithPadding

# Usando 'np' (NumPy) para evitar erro de detecção de backend
data_collator = DataCollatorWithPadding(tokenizer=tokenizador, return_tensors="np")

dados_treino = dataset_tokenizado["treino"].to_tf_dataset(
    columns=["attention_mask", "input_ids"],
    label_cols="label",
    shuffle=True,
    batch_size=16,
    collate_fn=data_collator
)

dados_validacao = dataset_tokenizado["teste"].to_tf_dataset(
    columns=["attention_mask", "input_ids"],
    label_cols="label",
    shuffle=False,
    batch_size=16,
    collate_fn=data_collator
)

print("Datasets preparados com sucesso!")

Datasets preparados com sucesso!

## Treinando um modelo

In [40]:
from transformers import create_optimizer

In [41]:
batch_size = 16
epocas = 2
batches_por_epoca = len(dataset_tokenizado['treino']) // batch_size
total_passos_treino = int(batches_por_epoca * epocas)
taxa_aprendizado = 2e-5

In [42]:
otimizador, scheduler = create_optimizer(
    init_lr = taxa_aprendizado, num_warmup_steps = 0, num_train_steps = total_passos_treino
)

modelo.compile(optimizer = otimizador)

In [43]:
modelo.fit(dados_treino, validation_data = dados_validacao, epochs= epocas)

Epoch 1/2
229/229 [==============================] - 297s 1s/step - loss: 1.8771 - val_loss: 1.7066
Epoch 2/2
229/229 [==============================] - 264s 1s/step - loss: 1.6565 - val_loss: 1.6401

### Metrica de perda

In [44]:
resultados_avaliacao = modelo.evaluate(dados_validacao)
print(f'Loss: {resultados_avaliacao}')

58/58 [==============================] - 21s 366ms/step - loss: 1.6401
Loss: 1.6400561332702637

## Publicando o modelo no Hugging Face

In [45]:
from huggingface_hub import notebook_login

notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [46]:
modelo.push_to_hub('distilbert-pt-cased-redacao-nota')

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /tmp/tmpsjvm3r9f/tf_model.h5:   0%|          |  559kB /  251MB

In [47]:
tokenizador.push_to_hub('distilbert-pt-cased-redacao-nota')

README.md: 0.00B [00:00, ?B/s]

CommitInfo(commit_url='https://huggingface.co/devBode/distilbert-pt-cased-redacao-nota/commit/2fe2112530837d31adb62c4a7e764252b005d009', commit_message='Upload tokenizer', commit_description='', oid='2fe2112530837d31adb62c4a7e764252b005d009', pr_url=None, repo_url=RepoUrl('https://huggingface.co/devBode/distilbert-pt-cased-redacao-nota', endpoint='https://huggingface.co', repo_type='model', repo_id='devBode/distilbert-pt-cased-redacao-nota'), pr_revision=None, pr_num=None)

# Utilizando o modelo para previsão

In [48]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

In [49]:
modelo = TFAutoModelForSequenceClassification.from_pretrained('devBode/distilbert-pt-cased-redacao-nota')

config.json:   0%|          | 0.00/845 [00:00<?, ?B/s]

tf_model.h5:   0%|          | 0.00/251M [00:00<?, ?B/s]

Some layers from the model checkpoint at devBode/distilbert-pt-cased-redacao-nota were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at devBode/distilbert-pt-cased-redacao-nota and are newly initialized: ['dropout_39']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [50]:
modelo = TFAutoModelForSequenceClassification.from_pretrained('devBode/distilbert-pt-cased-redacao-nota')
tokenizador = AutoTokenizer.from_pretrained('devBode/distilbert-pt-cased-redacao-nota')

Some layers from the model checkpoint at devBode/distilbert-pt-cased-redacao-nota were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at devBode/distilbert-pt-cased-redacao-nota and are newly initialized: ['dropout_59']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

In [51]:
dados_redacoes['teste'].to_pandas()

                                                 essay  score
0    O atual vírus que expandiu o Brasil está sendo...      7
1    No século XIX, Positivismo defendia o uso do m...      8
2    A Qualificação qualificação e o futuro do empr...      4
3    O homem com uma arma nas mãos é um bicho feroz...      7
4    Durante o período da Guerra Fria, ocorreu o ma...      7
..                                                 ...    ...
909  Com o início da era digital, a capacidade de t...      6
910  O feminicídio é o assassinato de uma mulher, a...      4
911  Foram vrias as conquistas que as mulheres bras...      5
912  Segundo o psicoterapeuta Ivan Carpelatto: “a v...      9
913  Promulgada em 1988, a Constituição Federal a e...      7

[914 rows x 2 columns]

In [52]:
textos = [dados_redacoes['teste']['essay'][2],
          dados_redacoes['teste']['essay'][909]]

In [53]:
import numpy as np

In [54]:
textos_tokenizados = tokenizador(textos, return_tensors = 'np', padding = 'longest')

In [55]:
resultados = modelo(textos_tokenizados).logits
resultados

<tf.Tensor: shape=(2, 11), dtype=float32, numpy=
array([[-0.5264313 , -1.3406626 , -0.23837265, -0.46486595,  1.7575438 ,
         1.9345651 ,  1.7250797 ,  0.20269042, -0.42137256, -1.1635349 ,
        -1.5092864 ],
       [-1.3803942 , -2.1079981 , -1.6823899 , -1.4770474 , -0.03209829,
         0.9608595 ,  2.19882   ,  1.8325565 ,  1.2603179 , -0.06857364,
        -1.2855611 ]], dtype=float32)>

In [56]:
classificacao = np.argmax(resultados, axis = 1)
print(classificacao)

[5 6]

In [60]:
from transformers import pipeline, AutoTokenizer, TFAutoModelForSequenceClassification

model_name = 'devBode/distilbert-pt-cased-redacao-nota'

# Explicitly load the TensorFlow model and tokenizer
loaded_tokenizer = AutoTokenizer.from_pretrained(model_name)
loaded_model = TFAutoModelForSequenceClassification.from_pretrained(model_name)

# Create the pipeline with the loaded TensorFlow model and tokenizer
classificador = pipeline(
    'text-classification',
    model=loaded_model,
    tokenizer=loaded_tokenizer,
    framework='tf'
)

Some layers from the model checkpoint at devBode/distilbert-pt-cased-redacao-nota were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at devBode/distilbert-pt-cased-redacao-nota and are newly initialized: ['dropout_79']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.
Device set to use 0

In [61]:
classificador(textos)

TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.

[{'label': '5', 'score': 0.3007186949253082},
 {'label': '6', 'score': 0.3698880970478058}]

## Construindo o aplicativo com Gradio

In [62]:
import gradio as gr

In [64]:
def mostrar_resultado(texto):
    if len(texto) < 400:
        return 'O texto precisa ter no mínimo 400 caracteres'
    return int(classificador(texto)[0]['label']) * 100

In [66]:
app = gr.Interface(
    fn = mostrar_resultado,
    inputs = gr.Textbox(label = 'Digite o texto'),
    outputs = gr.Textbox(label = 'Nota da redação'),
    title = 'Insira um texto para receber uma nota entre 0 e 1000'
)

app.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://5ca6fd2518634a2eb8.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [67]:
dados_redacoes['teste']['essay'][2]

'A Qualificação qualificação e o futuro do emprego estão cada vez mais preocupantes e eles são importantes para que nosso país saia dessa crise de desemprego, Cerca desemprego. Cerca de 12 milhões de pessoas atualmente estão desempregadas, por isso que o futuro é tão preocupante para alguns., Por tanto Portanto, é importante ressaltar que uma qualificação em alguma área e o ensino medio médio completo é essencial são essenciais para que a pessoa consiga um emprego, muitas emprego. Muitas vezes as empresas deixam de contratar o funcionário por conta de seu currículo não ter nenhuma qualificação., Atualmente a tecnologia é uma das ferramentas mais usadas, hoje em dia conseguimos fazer praticamente tudo com ela, porém o excesso dela pode ocasionar muitos problemas, um deles é a falta de emprego por conta de ser algo mais robotico e agil robótico e ágil., Infelizmente em outros países esse método já foi adotado nos mercados e industrias indústrias, substituindo o funcionário por algo mais moderno que para o empregador daria menos gastos, esse avanço da tecnologia ainda está em andamento em nosso país., Portanto, podemos concluir que uma qualificação é muito importante nos dias atuais, e a questão do emprego, deveriam criar mais empregos para suportar o numero número de população de desempregados e não substituir los por maquinas substituí-los por máquinas'