Começando a Aula de Python

In [ ]:
5

5

In [ ]:
print(5)

5

In [ ]:
print("Olá mundo!")

Olá mundo!

In [ ]:
# print("Olá mundo" + 5)

In [ ]:
print("Olá mundo" + " 5")

Olá mundo 5

In [ ]:
print(5 + 2)

7

In [ ]:
produto1 = 5

In [ ]:
print(produto1)

5

In [ ]:
produto2 = 2000

In [ ]:
print(produto2)

2000

In [ ]:
produto3 = 1

In [ ]:
print(produto1 + produto2 + produto3)

2006

In [ ]:
nome_do_produto1 = "Macarrão"
nome_do_produto2 = "Celular"
nome_do_produto3 = "Bala"

In [ ]:
print(nome_do_produto1 + " " + nome_do_produto2 + " " + nome_do_produto3)

Macarrão Celular Bala

In [ ]:
amigos = 5
aluguel = 1000
supermercado = 500
carro = 400

In [ ]:
total = aluguel + supermercado + carro

In [ ]:
print(total)

1900

In [ ]:
aluguel = 900

In [ ]:
print(total)

1900

In [ ]:
total = aluguel + supermercado + carro
print(total)

1800

In [ ]:
aluguel = aluguel - 100
total = aluguel + supermercado + carro
print(total)

1700

In [ ]:
amigos = 6
aluguel = 1000
supermercado = 500
carro = 400

In [ ]:
print(carro * 2)

800

In [ ]:
total_de_carros = carro * 2

In [ ]:
total = aluguel + supermercado + total_de_carros
print(total)

2300

In [ ]:
total_por_pessoa = total / amigos
print(total_por_pessoa)

383.3333333333333

In [ ]:
print(round(total_por_pessoa, 2))

383.33

In [ ]:
type(aluguel)

int

In [ ]:
type(total_por_pessoa)

float

In [ ]:
type(nome_do_produto1)

str

In [ ]:
pedro_tem_carteira_de_motorista = True
mario_tem_carteira_de_motorista = False

In [ ]:
type(pedro_tem_carteira_de_motorista)

bool

Inicial: "       Fabrício CaRRAro     da  ALura"

Final: "FABRÍCIO CARRARO DA ALURA"

In [ ]:
texto = "      Fabrício CaRRAro    da ALura"

In [ ]:
print(texto)

      Fabrício CaRRAro    da ALura

In [ ]:
print(texto.lower())

      fabrício carraro    da alura

In [ ]:
print(texto.upper())

      FABRÍCIO CARRARO    DA ALURA

In [ ]:
print(texto.strip())

Fabrício CaRRAro    da ALura

In [ ]:
print(texto.replace("    ", " "))

   Fabrício CaRRAro da ALura

In [ ]:
texto = texto.upper().strip().replace("    ", " ")

In [ ]:
print(texto)

FABRÍCIO CARRARO DA ALURA

In [ ]:
nome = input("Digite o seu nome: ")

Digite o seu nome: Renato

In [ ]:
idade = input("Digite a sua idade: ")

Digite a sua idade: 19

In [ ]:
type(nome)

str

In [ ]:
type(idade)

str

In [ ]:
idade = int(idade)

In [ ]:
type(idade)

int

In [ ]:
print("A pessoa se chama " + nome + " e tem " + str(idade) + " anos de idade")

A pessoa se chama Renato e tem 19 anos de idade

In [ ]:
print(f"A pessoa se chama {nome} e tem {idade} anos de idade")

A pessoa se chama Renato e tem 19 anos de idade

Estruturas Condicionas

In [ ]:
nome = input("Digite o seu nome: ")

Digite o seu nome: Renato

In [ ]:
idade = int(input("Digite a sua idade: "))

Digite a sua idade: 18

In [ ]:
type(idade)

int

In [ ]:
if idade >= 18:
    print(f"O {nome} pode entrar na festa porque ele é maior de idade.")
    print(f"Ele tem {idade} anos de idade.")
else:
    print(f"O {nome} NÃO pode entrar na festa porque ele é menor de idade.")
    print(f"Ele tem {idade} anos de idade.")

O Renato pode entrar na festa porque ele é maior de idade.
Ele tem 18 anos de idade.

In [ ]:
media = float(input("Digite a sua media: "))

if media >= 7.0:
  print("Aprovado")
elif media >= 5.0:
  print("Recuperação")
else:
  print("Reprovado")

Digite a sua media: 6.9
Recuperação

In [ ]:
media = float(input("Digite a sua media: "))

if media < 5.0:
  print("Reprovado")
elif media >= 5.0 and media < 7.0:
  print("Recuperação")
else:
  print("Aprovado")

Digite a sua media: 5.0
Recuperação

# Rodando a sua IA no Google Colab

In [ ]:
import os
from google.colab import userdata

os.environ['GOOGLE_API_KEY'] = userdata.get('GEMINI_KEY')

In [ ]:
from google import genai

client = genai.Client()

In [ ]:
resposta = client.models.generate_content(model="gemini-3.5-flash", contents="O que é a Inteligência Artificial?")

In [ ]:
print(resposta.text)

A **Inteligência Artificial (IA)** é um campo da ciência da computação que se dedica a criar sistemas, dispositivos e programas capazes de realizar tarefas que, normalmente, exigiriam a **inteligência humana**.

Em termos simples, a IA permite que as máquinas "pensem", aprendam com a experiência, adaptem-se a novas entradas de dados e tomem decisões de forma autônoma.

Para entender a IA de forma clara, podemos dividi-la em alguns pontos essenciais:

---

### 1. Como a IA funciona?
Ao contrário dos programas de computador tradicionais, que seguem regras rígidas e pré-programadas ("se acontecer A, faça B"), a IA funciona através de:

*   **Dados:** A IA precisa de um grande volume de informações para aprender (como imagens, textos, números).
*   **Algoritmos:** São as instruções matemáticas que a máquina usa para processar os dados.
*   **Aprendizado de Máquina (Machine Learning):** É a capacidade de a máquina identificar padrões nos dados e melhorar seu desempenho sozinha, sem ser explicitamente programada para isso.
*   **Aprendizado Profundo (Deep Learning):** Uma subárea do Machine Learning que usa redes neurais artificiais (inspiradas no cérebro humano) para resolver problemas complexos, como reconhecimento de voz e visão computacional.

---

### 2. Os dois grandes tipos de IA
Atualmente, a inteligência artificial é dividida em duas categorias principais:

*   **IA Estreita ou Fraca (ANI - Artificial Narrow Intelligence):** É a IA que temos hoje. Ela é projetada e treinada para realizar **uma tarefa específica** extremamente bem (ex: jogar xadrez, traduzir textos ou reconhecer rostos). Ela não tem consciência nem inteligência geral.
*   **IA Geral ou Forte (AGI - Artificial General Intelligence):** É uma IA teórica que teria a capacidade de compreender, aprender e aplicar conhecimento em qualquer tarefa intelectual, exatamente como um ser humano. **Ainda não existe.**

---

### 3. Exemplos de IA no seu dia a dia
Você provavelmente usa IA todos os dias sem perceber:

*   **Assistentes Virtuais:** Alexa, Siri e Google Assistente.
*   **Sistemas de Recomendação:** Os algoritmos da Netflix, Spotify, YouTube e Instagram, que sugerem o que você deve assistir ou ouvir.
*   **GPS e Rotas:** Waze e Google Maps, que calculam o trânsito em tempo real.
*   **Filtros de Spam:** No seu e-mail, identificando mensagens indesejadas.
*   **IA Generativa:** Ferramentas como o ChatGPT (que está respondendo a você agora), Midjourney (gerador de imagens) e tradutores automáticos.
*   **Reconhecimento Facial:** Para desbloquear o celular ou autorizar transações bancárias.

---

### 4. Por que a IA é tão importante hoje?
A IA está revolucionando a sociedade porque ela consegue processar bilhões de dados em segundos, algo que os humanos levariam anos para fazer. Ela está sendo usada para:
*   **Medicina:** Diagnosticar doenças como o câncer com maior precisão e rapidez.
*   **Mudanças Climáticas:** Prever desastres naturais e otimizar o uso de energia limpa.
*   **Indústria:** Automatizar tarefas repetitivas e perigosas.

---

### 5. Desafios e Ética
Apesar dos benefícios, a IA traz debates importantes:
*   **Desemprego:** A automação de tarefas pode extinguir algumas profissões (embora crie outras).
*   **Viés Algorítmico:** Se a IA aprender com dados humanos preconceituosos, ela pode tomar decisões discriminatórias.
*   **Privacidade:** A necessidade de grande volume de dados levanta questões sobre o uso de dados pessoais.

Em resumo, a Inteligência Artificial é uma ferramenta poderosa criada para **ampliar a capacidade humana**, transformando a tecnologia de algo que apenas executa ordens para algo que nos ajuda a resolver problemas complexos.

In [ ]:
chat = client.chats.create(model="gemini-3.5-flash")

In [ ]:
resposta = chat.send_message("Por onde começar estudar sobre Marchine Learning?")

In [ ]:
print(resposta.text)

Começar a estudar **Machine Learning (Aprendizado de Máquina)** pode parecer intimidador devido à quantidade de matemática e programação envolvidas. No entanto, o segredo é seguir um caminho estruturado, indo do mais simples ao mais complexo.

Aqui está um **roteiro passo a passo** testado e recomendado para começar do zero:

---

### Passo 1: Domine a Base (Os Pilares)

Antes de entrar nos algoritmos de Machine Learning, você precisa de duas ferramentas básicas:

1. **Programação (Python):**
   * Por que? Python é a linguagem padrão do mercado para IA.
   * O que aprender: Sintaxe básica, estruturas de dados (listas, dicionários), loops, funções e orientação a objetos.
   * *Onde estudar:* Curso em Vídeo (Gustavo Guanabara) no YouTube (grátis e em português).

2. **Matemática Essencial (Sem pânico!):**
   * Você não precisa ser um gênio da matemática, mas precisa entender os conceitos intuitivamente.
   * **Álgebra Linear:** Vetores, matrizes e multiplicação de matrizes.
   * **Estatística e Probabilidade:** Média, mediana, moda, desvio padrão, correlação e distribuições.
   * **Cálculo:** O conceito de derivada (ajuda a entender como os modelos aprendem).

---

### Passo 2: Manipulação e Visualização de Dados

Machine Learning é sobre dados. 80% do trabalho de um cientista de dados é limpar e preparar os dados. Aprenda as seguintes bibliotecas Python:

* **Pandas:** Para manipulação de tabelas (como se fosse um Excel programável).
* **NumPy:** Para computação matemática rápida.
* **Matplotlib e Seaborn:** Para criar gráficos e visualizar os dados.

---

### Passo 3: Conceitos Teóricos de Machine Learning

Entenda os conceitos fundamentais antes de codificar:

* **O que é Aprendizado Supervisionado:** (O modelo aprende com exemplos rotulados, ex: prever preço de casas).
* **O que é Aprendizado Não-Supervisionado:** (O modelo busca padrões em dados sem rótulos, ex: agrupar clientes semelhantes).
* **Conceitos de Overfitting (Sobreajuste) e Underfitting (Subajuste):** O equilíbrio entre decorar o treino e aprender de verdade.
* **Métricas de Avaliação:** Como saber se seu modelo é bom? (Acurácia, Precisão, Recall, MSE).

---

### Passo 4: Prática com Scikit-Learn

O **Scikit-Learn** é a biblioteca Python mais popular para Machine Learning clássico. Comece aplicando algoritmos simples:

* Regressão Linear (para prever números).
* Regressão Logística (para classificação, ex: sim ou não).
* Árvores de Decisão.
* K-Means (para agrupamento).

*Dica: Comece com datasets clássicos e fáceis, como o Iris Dataset (classificar flores) ou o Titanic Dataset (prever sobreviventes).*

---

### Passo 5: Cursos Recomendados (Do Iniciante ao Avançado)

Aqui estão as melhores fontes de aprendizado:

#### Gratuitos e Práticos:
* **Kaggle Learn:** Cursos rápidos, interativos e direto ao ponto sobre Python, Pandas e Machine Learning básico. Excelente para começar a programar rápido.
* **Curso de Machine Learning do Andrew Ng (Coursera):** É a "Bíblia" do Machine Learning. O professor Andrew Ng (co-fundador do Coursera e do Google Brain) explica a matemática por trás dos algoritmos de forma muito didática. (A versão atualizada usa Python).

#### Livros de Referência:
* **"Mãos à Obra: Aprendizado de Máquina com Scikit-Learn, Keras & TensorFlow"** (Aurélien Géron): O melhor livro prático sobre o assunto.

#### Canais no YouTube:
* **StatQuest com Josh Starmer:** Explica conceitos estatísticos e de ML com desenhos e de forma extremamente simples (em inglês, mas imperdível).
* **Seja um Data Scientist (Meigarom Lopes):** Excelente canal em português focado na prática do mercado de trabalho.

---

### Passo 6: Participe de Comunidades e Pratique

1. **Crie uma conta no GitHub:** Suba seus códigos para lá para criar seu portfólio.
2. **Entre no Kaggle:** Participe de competições para iniciantes (como a do Titanic). É a melhor forma de aprender com o código de outras pessoas.
3. **Faça projetos pessoais:** Escolha algo que você goste (ex: prever o resultado de jogos do seu time, classificar músicas do Spotify) e tente coletar os dados e aplicar um modelo.

### Resumo do plano de ação para esta semana:
1. Instale o **Anaconda** (que vem com o Jupyter Notebook e as principais bibliotecas).
2. Faça o curso gratuito de **Python** e **Intro to Machine Learning** no site do **Kaggle**.

In [ ]:
resposta = chat.send_message("O que é e pra que serve o scikit-learn?")

In [ ]:
print(resposta.text)

O **Scikit-learn** (frequentemente importado no código como `sklearn`) é a biblioteca de **Machine Learning** mais popular, utilizada e importante da linguagem Python.

Se você quer criar modelos de inteligência artificial para prever coisas, classificar dados ou agrupar clientes, o Scikit-learn é a ferramenta padrão que você vai usar.

Ele foi construído sobre outras bibliotecas científicas do Python, como **NumPy** (para computação matemática), **SciPy** (para ciência e engenharia) e **Matplotlib** (para gráficos).

---

### Para que serve o Scikit-learn?

O Scikit-learn serve para cobrir praticamente todas as etapas do desenvolvimento de um modelo de Machine Learning (exceto Deep Learning complexo). Ele é dividido em 6 grandes áreas:

#### 1. Classificação (Identificar a qual categoria um objeto pertence)
* **Para que serve:** Prever se um e-mail é spam ou não; prever se um cliente vai cancelar a assinatura (Churn); diagnosticar se um tumor é benigno ou maligno.
* **Algoritmos comuns:** Regressão Logística, Árvores de Decisão, Random Forest, SVM.

#### 2. Regressão (Prever um valor numérico contínuo)
* **Para que serve:** Prever o preço de uma casa com base no tamanho; prever o faturamento de uma empresa no próximo mês; prever a temperatura de amanhã.
* **Algoritmos comuns:** Regressão Linear, Ridge, Lasso.

#### 3. Agrupamento / Clustering (Agrupar objetos semelhantes de forma automática)
* **Para que serve:** Segmentar clientes de um e-commerce em grupos de consumo (sem dar rótulos prévios); agrupar notícias por temas parecidos.
* **Algoritmos comuns:** K-Means, DBSCAN.

#### 4. Pré-processamento de Dados (Preparar os dados para o modelo)
* **Para que serve:** Os computadores só entendem números. O Scikit-learn ajuda a transformar textos em números, normalizar escalas (ex: transformar idades e salários para uma mesma escala de 0 a 1) e lidar com dados que estão faltando.

#### 5. Seleção e Avaliação de Modelos (Testar se o modelo é bom)
* **Para que serve:** Dividir seus dados em "treino" e "teste", fazer validação cruzada (Cross-Validation) e calcular métricas como Acurácia, Precisão e F1-Score para saber se o seu modelo realmente funciona.

#### 6. Redução de Dimensionalidade (Simplificar os dados)
* **Para que serve:** Reduzir o número de variáveis de um problema para torná-lo mais rápido de processar, sem perder as informações mais importantes.
* **Algoritmos comuns:** PCA (Análise de Componentes Principais).

---

### Por que o Scikit-learn é tão famoso?

1. **Fácil de usar (Interface Consistente):** Quase todos os modelos no Scikit-learn funcionam com a mesma lógica de três passos:
   * `.fit()`: Treina o modelo com os dados.
   * `.predict()`: Faz previsões com o modelo treinado.
   * `.score()`: Avalia o desempenho do modelo.
2. **Documentação Incrível:** A documentação do Scikit-learn é considerada uma das melhores do mundo da programação. Ela tem exemplos visuais, tutoriais e explicações teóricas de cada algoritmo.
3. **Gratuito e de Código Aberto:** Qualquer pessoa ou empresa (como Spotify, Booking e J.P. Morgan) pode usar comercialmente sem pagar nada.

---

### Um exemplo prático de código

Veja como é simples criar um modelo que aprende a classificar se uma flor é de um tipo ou de outro usando apenas 6 linhas de código útil:

```python
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

# 1. Carrega os dados (no caso, dados de flores Iris)
dados = load_iris()
X, y = dados.data, dados.target

# 2. Divide os dados em treino (80%) e teste (20%)
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2)

# 3. Cria o modelo (Árvore de Decisão)
modelo = DecisionTreeClassifier()

# 4. Treina o modelo (O aprendizado acontece aqui!)
modelo.fit(X_treino, y_treino)

# 5. Faz previsões com os dados de teste que o modelo nunca viu
previsoes = modelo.predict(X_teste)

# 6. Avalia a acurácia do modelo
acuracia = modelo.score(X_teste, y_teste)
print(f"Precisão do modelo: {acuracia * 100:.2f}%")
```

### O que o Scikit-learn **NÃO** faz?
Ele **não** é focado em **Deep Learning** (Redes Neurais Profundas para reconhecimento de imagens complexas, geração de texto como o ChatGPT, áudio, etc.). Para essas tarefas de IA avançada, utilizam-se outras bibliotecas como **TensorFlow** ou **PyTorch**.

In [ ]:
chat.get_history()

[UserContent(
   parts=[
     Part(
       text='Por onde começar estudar sobre Marchine Learning?'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text="""Começar a estudar **Machine Learning (Aprendizado de Máquina)** pode parecer intimidador devido à quantidade de matemática e programação envolvidas. No entanto, o segredo é seguir um caminho estruturado, indo do mais simples ao mais complexo.

 Aqui está um **roteiro passo a passo** testado e recomendado para começar do zero:

 ---

 ### Passo 1: Domine a Base (Os Pilares)

 Antes de entrar nos algoritmos de Machine Learning, você precisa de duas ferramentas básicas:

 1. **Programação (Python):**
    * Por que? Python é a linguagem padrão do mercado para IA.
    * O que aprender: Sintaxe básica, estruturas de dados (listas, dicionários), loops, funções e orientação a objetos.
    * *Onde estudar:* Curso em Vídeo (Gustavo Guanabara) no YouTube (grátis e em português).

 2. **Matemática Essencial (Sem pânico!):**
    * Você não precisa ser um gênio da matemática, mas precisa entender os conceitos intuitivamente.
    * **Álgebra Linear:** Vetores, matrizes e multiplicação de matrizes.
    * **Estatística e Probabilidade:** Média, mediana, moda, desvio padrão, correlação e distribuições.
    * **Cálculo:** O conceito de derivada (ajuda a entender como os modelos aprendem).

 ---

 ### Passo 2: Manipulação e Visualização de Dados

 Machine Learning é sobre dados. 80% do trabalho de um cientista de dados é limpar e preparar os dados. Aprenda as seguintes bibliotecas Python:

 * **Pandas:** Para manipulação de tabelas (como se fosse um Excel programável).
 * **NumPy:** Para computação matemática rápida.
 * **Matplotlib e Seaborn:** Para criar gráficos e visualizar os dados.

 ---

 ### Passo 3: Conceitos Teóricos de Machine Learning

 Entenda os conceitos fundamentais antes de codificar:

 * **O que é Aprendizado Supervisionado:** (O modelo aprende com exemplos rotulados, ex: prever preço de casas).
 * **O que é Aprendizado Não-Supervisionado:** (O modelo busca padrões em dados sem rótulos, ex: agrupar clientes semelhantes).
 * **Conceitos de Overfitting (Sobreajuste) e Underfitting (Subajuste):** O equilíbrio entre decorar o treino e aprender de verdade.
 * **Métricas de Avaliação:** Como saber se seu modelo é bom? (Acurácia, Precisão, Recall, MSE).

 ---

 ### Passo 4: Prática com Scikit-Learn

 O **Scikit-Learn** é a biblioteca Python mais popular para Machine Learning clássico. Comece aplicando algoritmos simples:

 * Regressão Linear (para prever números).
 * Regressão Logística (para classificação, ex: sim ou não).
 * Árvores de Decisão.
 * K-Means (para agrupamento).

 *Dica: Comece com datasets clássicos e fáceis, como o Iris Dataset (classificar flores) ou o Titanic Dataset (prever sobreviventes).*

 ---

 ### Passo 5: Cursos Recomendados (Do Iniciante ao Avançado)

 Aqui estão as melhores fontes de aprendizado:

 #### Gratuitos e Práticos:
 * **Kaggle Learn:** Cursos rápidos, interativos e direto ao ponto sobre Python, Pandas e Machine Learning básico. Excelente para começar a programar rápido.
 * **Curso de Machine Learning do Andrew Ng (Coursera):** É a "Bíblia" do Machine Learning. O professor Andrew Ng (co-fundador do Coursera e do Google Brain) explica a matemática por trás dos algoritmos de forma muito didática. (A versão atualizada usa Python).

 #### Livros de Referência:
 * **"Mãos à Obra: Aprendizado de Máquina com Scikit-Learn, Keras & TensorFlow"** (Aurélien Géron): O melhor livro prático sobre o assunto.

 #### Canais no YouTube:
 * **StatQuest com Josh Starmer:** Explica conceitos estatísticos e de ML com desenhos e de forma extremamente simples (em inglês, mas imperdível).
 * **Seja um Data Scientist (Meigarom Lopes):** Excelente canal em português focado na prática do mercado de trabalho.

 ---

 ### Passo 6: Participe de Comunidades e Pratique

 1. **Crie uma conta no GitHub:** Suba seus códigos para lá para criar seu portfólio.
 2. **Entre no Kaggle:** Participe de competições para iniciantes (como a do Titanic). É a melhor forma de aprender com o código de outras pessoas.
 3. **Faça projetos pessoais:** Escolha algo que você goste (ex: prever o resultado de jogos do seu time, classificar músicas do Spotify) e tente coletar os dados e aplicar um modelo.

 ### Resumo do plano de ação para esta semana:
 1. Instale o **Anaconda** (que vem com o Jupyter Notebook e as principais bibliotecas).
 2. Faça o curso gratuito de **Python** e **Intro to Machine Learning** no site do **Kaggle**.""",
       thought_signature=b'\x12\xd1\x1c\n\xce\x1c\x01\x0c9\xd6\xc7\x8f\xad\xfat\xa2?kiA\xb5j\xef\xd8\xb7\x8fby\xc0z\x0c\xc7\x95\xae\xa0\xe2\xf8>Xoo\xcf\xa9\x95\xcb\x0f!\x1b^\x8f\xa6\xc5\x98)\x01\xc1`\x02\xfc\xae\r\x9b\xe2C4uH\xc0\xba\x01K1\x90\xb25PG\xd3v\n\x98v\x92\xfa\x85nH\x86~\x8f\xf3z;+\x8e\xd9c...'
     ),
   ],
   role='model'
 ),
 UserContent(
   parts=[
     Part(
       text='O que é e pra que serve o scikit-learn?'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text="""O **Scikit-learn** (frequentemente importado no código como `sklearn`) é a biblioteca de **Machine Learning** mais popular, utilizada e importante da linguagem Python.

 Se você quer criar modelos de inteligência artificial para prever coisas, classificar dados ou agrupar clientes, o Scikit-learn é a ferramenta padrão que você vai usar.

 Ele foi construído sobre outras bibliotecas científicas do Python, como **NumPy** (para computação matemática), **SciPy** (para ciência e engenharia) e **Matplotlib** (para gráficos).

 ---

 ### Para que serve o Scikit-learn?

 O Scikit-learn serve para cobrir praticamente todas as etapas do desenvolvimento de um modelo de Machine Learning (exceto Deep Learning complexo). Ele é dividido em 6 grandes áreas:

 #### 1. Classificação (Identificar a qual categoria um objeto pertence)
 * **Para que serve:** Prever se um e-mail é spam ou não; prever se um cliente vai cancelar a assinatura (Churn); diagnosticar se um tumor é benigno ou maligno.
 * **Algoritmos comuns:** Regressão Logística, Árvores de Decisão, Random Forest, SVM.

 #### 2. Regressão (Prever um valor numérico contínuo)
 * **Para que serve:** Prever o preço de uma casa com base no tamanho; prever o faturamento de uma empresa no próximo mês; prever a temperatura de amanhã.
 * **Algoritmos comuns:** Regressão Linear, Ridge, Lasso.

 #### 3. Agrupamento / Clustering (Agrupar objetos semelhantes de forma automática)
 * **Para que serve:** Segmentar clientes de um e-commerce em grupos de consumo (sem dar rótulos prévios); agrupar notícias por temas parecidos.
 * **Algoritmos comuns:** K-Means, DBSCAN.

 #### 4. Pré-processamento de Dados (Preparar os dados para o modelo)
 * **Para que serve:** Os computadores só entendem números. O Scikit-learn ajuda a transformar textos em números, normalizar escalas (ex: transformar idades e salários para uma mesma escala de 0 a 1) e lidar com dados que estão faltando.

 #### 5. Seleção e Avaliação de Modelos (Testar se o modelo é bom)
 * **Para que serve:** Dividir seus dados em "treino" e "teste", fazer validação cruzada (Cross-Validation) e calcular métricas como Acurácia, Precisão e F1-Score para saber se o seu modelo realmente funciona.

 #### 6. Redução de Dimensionalidade (Simplificar os dados)
 * **Para que serve:** Reduzir o número de variáveis de um problema para torná-lo mais rápido de processar, sem perder as informações mais importantes.
 * **Algoritmos comuns:** PCA (Análise de Componentes Principais).

 ---

 ### Por que o Scikit-learn é tão famoso?

 1. **Fácil de usar (Interface Consistente):** Quase todos os modelos no Scikit-learn funcionam com a mesma lógica de três passos:
    * `.fit()`: Treina o modelo com os dados.
    * `.predict()`: Faz previsões com o modelo treinado.
    * `.score()`: Avalia o desempenho do modelo.
 2. **Documentação Incrível:** A documentação do Scikit-learn é considerada uma das melhores do mundo da programação. Ela tem exemplos visuais, tutoriais e explicações teóricas de cada algoritmo.
 3. **Gratuito e de Código Aberto:** Qualquer pessoa ou empresa (como Spotify, Booking e J.P. Morgan) pode usar comercialmente sem pagar nada.

 ---

 ### Um exemplo prático de código

 Veja como é simples criar um modelo que aprende a classificar se uma flor é de um tipo ou de outro usando apenas 6 linhas de código útil:

 ```python
 from sklearn.datasets import load_iris
 from sklearn.model_selection import train_test_split
 from sklearn.tree import DecisionTreeClassifier

 # 1. Carrega os dados (no caso, dados de flores Iris)
 dados = load_iris()
 X, y = dados.data, dados.target

 # 2. Divide os dados em treino (80%) e teste (20%)
 X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2)

 # 3. Cria o modelo (Árvore de Decisão)
 modelo = DecisionTreeClassifier()

 # 4. Treina o modelo (O aprendizado acontece aqui!)
 modelo.fit(X_treino, y_treino)

 # 5. Faz previsões com os dados de teste que o modelo nunca viu
 previsoes = modelo.predict(X_teste)

 # 6. Avalia a acurácia do modelo
 acuracia = modelo.score(X_teste, y_teste)
 print(f"Precisão do modelo: {acuracia * 100:.2f}%")
 ```

 ### O que o Scikit-learn **NÃO** faz?
 Ele **não** é focado em **Deep Learning** (Redes Neurais Profundas para reconhecimento de imagens complexas, geração de texto como o ChatGPT, áudio, etc.). Para essas tarefas de IA avançada, utilizam-se outras bibliotecas como **TensorFlow** ou **PyTorch**.""",
       thought_signature=b'\x12\x88\x1b\n\x85\x1b\x01\x0c9\xd6\xc7\xb9.y\x18\xfe\xfb\xa5EB\xa3\x06|k\xe2:\x98@*\x07S(#\xf3\xc9Ka\x99:\x10X\xe0i\xc28\xda\xa4\xf2\x04|\x8d\xa7\xd9D,D\xaa\xd1\x1f\xa8$P\xc0\xbf\x1f]Hff$[\xf0t\xb0\x8bY9(G\x05\xcf\xb6\xd5RK\xa2\xfa\xa2J\xd2b\x8c\xef\xa5\xaa\x08\xf5...'
     ),
   ],
   role='model'
 )]

In [ ]:
chat = client.chats.create(model="gemini-2.5-flash")
prompt = input("Digite a sua pergunta: ")

Digite a sua pergunta: Quem nasceu primeiro o ovo ou a galinha?

In [ ]:
while prompt != "fim":
  resposta = chat.send_message(prompt)
  print(resposta.text)
  print("\n")
  prompt = input("Digite a sua pergunta: ")

Essa é uma daquelas perguntas clássicas que sempre geram debate! Do ponto de vista da ciência e da evolução, a resposta é: **o ovo veio primeiro**.

Vamos entender por quê:

1.  **Ovo em sentido amplo:** Muito antes das galinhas existirem, outras espécies (dinossauros, répteis, outras aves ancestrais) já botavam ovos. O ovo amniótico (com casca rígida ou flexível, que permite ao embrião se desenvolver em terra) surgiu centenas de milhões de anos antes da galinha. Então, "o ovo" como forma de reprodução é muito mais antigo que a galinha.

2.  **Ovo da galinha (o que contém a galinha):** As espécies evoluem gradualmente. Houve um ponto em que os ancestrais das galinhas (proto-galinhas) acasalaram. O embrião dentro de um desses ovos sofreu uma pequena mutação genética (ou a acumulação de pequenas mutações ao longo de gerações) que o tornou o primeiro indivíduo da espécie *Gallus gallus domesticus* – ou seja, a primeira galinha moderna.

    *   Essa primeira galinha só poderia ter nascido de um ovo.
    *   Esse ovo foi posto por um animal que era **quase** uma galinha, mas ainda não era *tecnicamente* uma galinha (era um ancestral muito próximo).
    *   Portanto, o ovo que continha o primeiro embrião de galinha veio antes da primeira galinha em si.

Em resumo, um animal que era "quase uma galinha" botou um ovo, e desse ovo nasceu a primeira "galinha" como a conhecemos hoje. Portanto, o ovo (contendo a primeira galinha) veio primeiro que a galinha.


Digite a sua pergunta: fim

# Estruturas de Repetição, Laços, Loops

In [ ]:
n = 1

while n <= 10:
  print("*" * n)
  n += 1

*
**
***
****
*****
******
*******
********
*********
**********

# Estruturas de dados

Listas

In [ ]:
lista_de_nomes = ["João CLeber", "Maria Silva", "Pedro Afonso", "Daniel Lopes", "Debora Carvalho"]

In [ ]:
lista_de_nomes[3]

'Daniel Lopes'

In [ ]:
lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

In [ ]:
print(lista_de_medias[3])

1.4

Desafio: Crie um código que percorra a lista de médias e some 1 em cada valor, exceto quando o valor passar de 10.0, que aí ele deve parar em 10.0

In [ ]:
for media in lista_de_medias:
  media += 1
  if media > 10.0:
    media = 10.0
  print(media)

9.9
8.5
5.2
2.4
10.0

In [ ]:
n = 0
lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

while n < len(lista_de_medias):
  lista_de_medias[n] += 1.0
  if lista_de_medias[n] > 10.0:
    lista_de_medias[n] = 10.0

  n += 1

print(lista_de_medias)

[9.9, 8.5, 5.2, 2.4, 10.0]

In [ ]:
len(lista_de_medias)

5

In [ ]:
lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

In [ ]:
lista_de_medias[-1]

9.5

In [ ]:
lista_de_medias[-2]

1.4

Particionando uma lista

In [ ]:
lista_de_nomes = ["João CLeber", "Maria Silva", "Pedro Afonso", "Daniel Lopes", "Debora Carvalho"]

In [ ]:
lista_de_nomes[1:3]

['Maria Silva', 'Pedro Afonso']

In [ ]:
lista_de_nomes[:3]

['João CLeber', 'Maria Silva', 'Pedro Afonso']

In [ ]:
lista_de_nomes[2:]

['Pedro Afonso', 'Daniel Lopes', 'Debora Carvalho']

In [ ]:
lista_de_nomes

['João CLeber',
 'Maria Silva',
 'Pedro Afonso',
 'Daniel Lopes',
 'Debora Carvalho']

In [ ]:
lista_de_nomes.append("Fabio Carraro")

In [ ]:
lista_de_nomes

['João CLeber',
 'Maria Silva',
 'Pedro Afonso',
 'Daniel Lopes',
 'Debora Carvalho',
 'Fabio Carraro']

In [ ]:
lista_de_nomes.extend(["Paulo Silveira", "Joana Garcia"])

In [ ]:
lista_de_nomes

['João CLeber',
 'Maria Silva',
 'Pedro Afonso',
 'Daniel Lopes',
 'Debora Carvalho',
 'Fabio Carraro',
 'Paulo Silveira',
 'Joana Garcia']

In [ ]:
lista_de_nomes.append(["Paulo Silveira", "Joana Garcia"])

In [ ]:
lista_de_nomes

['João CLeber',
 'Maria Silva',
 'Pedro Afonso',
 'Daniel Lopes',
 'Debora Carvalho',
 'Fabio Carraro',
 'Paulo Silveira',
 'Joana Garcia',
 ['Paulo Silveira', 'Joana Garcia']]

In [ ]:
lista_de_nomes[-1][1]

'Joana Garcia'

In [ ]:
lista_de_nomes.remove(['Paulo Silveira', 'Joana Garcia'])

In [ ]:
lista_de_nomes

['João CLeber',
 'Maria Silva',
 'Pedro Afonso',
 'Daniel Lopes',
 'Debora Carvalho',
 'Fabio Carraro',
 'Paulo Silveira',
 'Joana Garcia']

In [ ]:
lista_de_nomes.pop(-2)
lista_de_nomes

['João CLeber',
 'Maria Silva',
 'Pedro Afonso',
 'Daniel Lopes',
 'Debora Carvalho',
 'Fabio Carraro',
 'Joana Garcia']

*Dicionario*</br> chave: valor

In [ ]:
lista_de_nomes = ["João CLeber", "Maria Silva", "Pedro Afonso", "Daniel Lopes", "Debora Carvalho"]
lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

In [ ]:
dict_nomes_medias = {}
for nome, media in zip(lista_de_nomes, lista_de_medias):
  dict_nomes_medias[nome] = media

In [ ]:
print(dict_nomes_medias)

{'João CLeber': 8.9, 'Maria Silva': 7.5, 'Pedro Afonso': 4.2, 'Daniel Lopes': 1.4, 'Debora Carvalho': 9.5}

In [ ]:
dict_nomes_medias["João CLeber"]

8.9

In [ ]:
dict_nomes_medias.get("Pedro Afonso")

4.2

In [ ]:
dict_nomes_medias.pop("Debora Carvalho")

9.5

In [ ]:
dict_nomes_medias

{'João CLeber': 8.9,
 'Maria Silva': 7.5,
 'Pedro Afonso': 4.2,
 'Daniel Lopes': 1.4}

In [ ]:
dict_nomes_medias.items()

dict_items([('João CLeber', 8.9), ('Maria Silva', 7.5), ('Pedro Afonso', 4.2), ('Daniel Lopes', 1.4)])

In [ ]:
dict_nomes_medias.keys()

dict_keys(['João CLeber', 'Maria Silva', 'Pedro Afonso', 'Daniel Lopes'])

In [ ]:
dict_nomes_medias.values()

dict_values([8.9, 7.5, 4.2, 1.4])

Desafio: Usar dicionarios de forma que as chaves sejam "nome" e "media" e os valores, sejamos nomes e media dos alunos

In [ ]:
lista_de_nomes = ["João CLeber", "Maria Silva", "Pedro Afonso", "Daniel Lopes", "Debora Carvalho"]
lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]
lista_completa = []
for nome, media in zip(lista_de_nomes, lista_de_medias):
  lista_completa.append({
      "nome": nome,
      "media": media
  })

print(lista_completa)

[{'nome': 'João CLeber', 'media': 8.9}, {'nome': 'Maria Silva', 'media': 7.5}, {'nome': 'Pedro Afonso', 'media': 4.2}, {'nome': 'Daniel Lopes', 'media': 1.4}, {'nome': 'Debora Carvalho', 'media': 9.5}]

In [ ]:
lista_completa[2]

{'nome': 'Pedro Afonso', 'media': 4.2}

In [ ]:
lista_completa[2]['media']

4.2

In [ ]:
dict_chave_composta = {}
for nome, media in zip(lista_de_nomes, lista_de_medias):
  dict_chave_composta[f"{nome}:{media}"] = {
      "nome": nome,
      "media": media
  }

print(dict_chave_composta)

{'João CLeber:8.9': {'nome': 'João CLeber', 'media': 8.9}, 'Maria Silva:7.5': {'nome': 'Maria Silva', 'media': 7.5}, 'Pedro Afonso:4.2': {'nome': 'Pedro Afonso', 'media': 4.2}, 'Daniel Lopes:1.4': {'nome': 'Daniel Lopes', 'media': 1.4}, 'Debora Carvalho:9.5': {'nome': 'Debora Carvalho', 'media': 9.5}}

# Estrutura de repetição 'For'

In [ ]:
dict_desafio = [
    {"nome": "Maria Silva", "media": 8.9},
    {"nome": "João Cleber", "media": 7.5},
    {"nome": "Ana Oliveira", "media": 4.2},
    {"nome": "Pedro Costa", "media": 1.4}
]

In [ ]:
n = 0

while n < len(dict_desafio):
  print(dict_desafio[n])
  n += 1

{'nome': 'Maria Silva', 'media': 8.9}
{'nome': 'João Cleber', 'media': 7.5}
{'nome': 'Ana Oliveira', 'media': 4.2}
{'nome': 'Pedro Costa', 'media': 1.4}

In [ ]:
for elemento in dict_desafio:
  print(elemento)

{'nome': 'Maria Silva', 'media': 8.9}
{'nome': 'João Cleber', 'media': 7.5}
{'nome': 'Ana Oliveira', 'media': 4.2}
{'nome': 'Pedro Costa', 'media': 1.4}

In [ ]:
for n in range(5):
  print(n)

0
1
2
3
4

In [ ]:
for n in range(2, 7):
  print(n)

2
3
4
5
6

In [ ]:
for n in range(1, 10, 2):
  print(n)

1
3
5
7
9

In [ ]:
pessoa = {
    "nome": "Renato",
    "idade": 19,
    "altura": 1.87
}

print(pessoa)

{'nome': 'Renato', 'idade': 19, 'altura': 1.87}

In [ ]:
for chave, valor in pessoa.items():
  print(f"A chave é {chave} e o valor é {valor}")

A chave é nome e o valor é Renato
A chave é idade e o valor é 19
A chave é altura e o valor é 1.87

In [ ]:
for n in range(11):
  if n % 2 == 0:
    print(n)

0
2
4
6
8
10

In [ ]:
for n in range(11):
  if n % 3 == 0:
    print(n)

0
3
6
9

# Funções

In [ ]:
texto2 = "   mArIa   dA  sIlVa    sAnToS  "
texto3 = "jOãO   pEdRo    dE oLiVeIrA       "
texto4 = "       AnA   cArOlInA bArBoSa mEnDeS"
texto5 = "  cArLoS   eDuArDo   dos  sAnToS    fIlHo   "
texto6 = "bEaTrIz    aPaReCiDa    RIbEiRo"

In [ ]:
def escreve_texto_corretamente(texto):
  texto_novo = texto.strip().upper().replace("  ", " ")
  print(texto_novo)

In [ ]:
escreve_texto_corretamente(texto2)

MARIA DA SILVA SANTOS

In [ ]:
texto2.split()

['mArIa', 'dA', 'sIlVa', 'sAnToS']

In [ ]:
def escreve_texto_corretamente(texto):
  texto_novo = texto.strip().upper()
  lista_de_palavras = texto_novo.split()
  print(lista_de_palavras)

In [ ]:
escreve_texto_corretamente(texto2)

['MARIA', 'DA', 'SILVA', 'SANTOS']

In [ ]:
def escreve_texto_corretamente(texto):
  texto_novo = texto.strip().upper()
  lista_de_palavras = texto_novo.split()
  texto_final = " ".join(lista_de_palavras)
  print(texto_final)

In [ ]:
escreve_texto_corretamente(texto2)

MARIA DA SILVA SANTOS

In [ ]:
escreve_texto_corretamente(texto3)

JOÃO PEDRO DE OLIVEIRA

In [ ]:
def escreve_texto_corretamente(texto):
  return " ".join(texto.upper().split())

In [ ]:
escreve_texto_corretamente(texto3)

'JOÃO PEDRO DE OLIVEIRA'

In [ ]:
salas_de_aula = ["Sala 1", "Sala 2", "Sala 3"]

In [ ]:
import random

def aloca_alunos_em_salas(nome_do_aluno, lista_de_salas):
  sala_escolhida = random.choice(lista_de_salas)
  return {"nome": nome_do_aluno, "sala": sala_escolhida}

In [ ]:
aloca_alunos_em_salas(texto2, salas_de_aula)

{'nome': '   mArIa   dA  sIlVa    sAnToS  ', 'sala': 'Sala 3'}

In [ ]:
nome_formatado = escreve_texto_corretamente(texto3)
print(nome_formatado)

JOÃO PEDRO DE OLIVEIRA

In [ ]:
aloca_alunos_em_salas(nome_formatado, salas_de_aula)

{'nome': 'JOÃO PEDRO DE OLIVEIRA', 'sala': 'Sala 2'}

# Desafio

####  1. Pedir pra uma IA gerar em Python uma lista de 20 emails pra você.
####  2. Criar uma função que vai receber como argumento/parâmetro uma lista de emails, percorrer essa lista de emails, e, para cada email da lista, ela irá chamar a IA do Gemini via API e pedir pra ela resumir para você todos os emails em apenas 1 linha, definindo o que essa pessoa queria no email.

In [8]:
emails = [
    """
    Olá, Cliente.
    Notificamos que uma nova chave Pix (celular) foi cadastrada na sua conta digital hoje às 14:32.
    Se foi você quem realizou essa operação, desconsidere este aviso.
    Caso não reconheça essa ação, entre em contato imediatamente com nossa central de atendimento pelo app.
    """,
    """
    E aí, galera! Beleza?
    Tô organizando o churrasco de aniversário aqui em casa no sábado, a partir das 13h.
    Vou comprar as carnes e as bebidas e depois a gente racha o valor por Pix.
    Conseguem me confirmar até amanhã quem vai conseguir colar? Valeu!
    """,
    """
    AWS CloudWatch Alarm Trigger:
    Metric Name: CPUUtilization
    Namespace: AWS/EC2
    Statistic: Average
    Threshold: Greater than 90% for 3 consecutive periods of 5 minutes.
    Current Value: 94.2%
    Action: Escalating to DevOps on-call team page.
    """,
    """
    Olá amigo!!! Você quer mudar de vida?? Temos vagas abertas para trabalhar apenas 2 horas por dia usando o seu celular!!! Não precisa de experiência prévia. Lucro garantido logo na primeira semana!!! CLIQUE AQUI AGORA para se cadastrar antes que as vagas terminem!!!
    """,
    """
    Prezados colaboradores,

    Informamos que o período de migração do plano de saúde empresarial termina nesta sexta-feira.
    Caso deseje incluir dependentes ou alterar sua acomodação, por favor envie o formulário preenchido e assinado para a nossa equipe até as 17h.

    Atenciosamente,
    Departamento de Recursos Humanos.
    """,
    # """
    # Fala, Thiago. Beleza?

    # Sobre o chamado da lentidão na VPN que você abriu: identificamos uma instabilidade na rota do servidor principal da região Sudeste.
    # Nossa equipe de infraestrutura já aplicou uma correção temporária e o tráfego deve normalizar nos próximos 15 minutos.
    # Pode testar novamente por aí?

    # Abraços,
    # Lucas - Suporte N2
    # """,
    # """
    # Aproveite a nossa queima de estoque exclusiva!
    # O smartphone que você estava namorando, smart TVs 4K e notebooks de última geração com descontos imperdíveis de até 70%.
    # Não perca tempo, os estoques são limitados.
    # Clique no link abaixo e use o cupom QUERO10 para mais 10% de desconto extra.
    # """,
    # """
    # Prezado(a) condômino(a),

    # Segue em anexo o boleto bancário referente à taxa condominial com vencimento para o dia 10/06/2026.
    # Lembramos que o pagamento após o vencimento acarretará multa de 2% e juros de 1% ao mês.
    # Caso já tenha efetuado o pagamento, favor desconsiderar este e-mail.
    # """,
    # """
    # The following pull request was successfully merged by the repository maintainer:

    # Repository: company-project/core-api
    # PR #14: Fix/race-condition-on-checkout
    # Merged by: @senior-dev-marcos

    # You can view the full details and diff on GitHub.
    # This notification was sent based on your watch settings.
    # """,
    # """
    # Olá!

    # Acelere sua carreira com a nossa nova pós-graduação focada em IA, Arquitetura de Software e Agentes Inteligentes.
    # Aprenda na prática com professores renomados do mercado e turbine seu portfólio.
    # As vagas para a turma deste semestre são limitadas.
    # Inscreva-se hoje mesmo com 20% de desconto na matrícula!
    # """,
    # """
    # Parabéns! Sua reserva para 3 diárias no Copacabana Palace está confirmada.

    # Check-in: 14/07/2026 às 14:00
    # Check-out: 17/07/2026 às 12:00
    # Número da reserva: 948.102.391

    # O pagamento será feito diretamente no balcão do hotel.
    # Desejamos uma excelente viagem!
    # """,
    # """
    # Falta pouco para a sua fome acabar!

    # O entregador Carlos R. acabou de retirar o seu pedido (Nº 5821 - 10 coxinhas de frango e 1 refrigerante) e já está se deslocando para o seu endereço.
    # Você pode acompanhar o trajeto da moto em tempo real pelo mapa do nosso aplicativo.
    # Código de entrega para informar ao motoboy: 7421.
    # """,
    # """
    # Olá.

    # Não conseguimos processar o pagamento da sua assinatura mensal do plano Premium no valor de R$ 55,90 com o cartão de crédito final 4321.
    # Para evitar a suspensão imediata das suas telas e do seu histórico, por favor acesse as configurações da sua conta e atualize a forma de pagamento.
    # """,
    # """
    # Time,

    # Na próxima segunda-feira, às 10h, teremos nossa reunião geral para definição e alinhamento das OKRs do terceiro trimestre (Q3).
    # Peço que cada líder de tribo/squad traga os rascunhos das metas de suas respectivas áreas revisados até o final desta semana.
    # O convite com o link do Meet já foi enviado.
    # """,
    # """
    # Olá, atleta!

    # Notamos que você não frequenta a nossa unidade há mais de 30 dias.
    # Sabemos que a rotina é corrida, mas a sua saúde não pode ficar em segundo plano!
    # Para te incentivar a voltar com tudo, preparamos a isenção da taxa de manutenção anual se você reativar seu plano até este sábado.
    # Te esperamos na área de musculação!
    # """,
    # """
    # Prezado cliente,

    # Identificamos que ainda faltam alguns comprovantes de despesas médicas e o informe de rendimentos da sua conta de investimentos no exterior para finalizarmos a retificação da sua declaração de Imposto de Renda.
    # Solicitamos o envio desses arquivos até quarta-feira para evitar cair na malha fina.
    # """,
    # """
    # Oi, filho! Segue a receita do bolo que você me pediu ontem:

    # 3 cenouras médias picadas
    # 3 ovos
    # 1 xícara de óleo
    # 2 xícaras de açúcar
    # 2 xícaras de farinha de trigo
    # 1 colher de fermento

    # Bate a cenoura, os ovos e o óleo no liquidificador, depois mistura o resto na mão. Assa por uns 40 minutos. Me avisa se deu certo! Beijos, te amo.
    # """,
    # """
    # Na edição desta semana da TechTrends, analisamos como as novas arquiteturas de Agentic Context Engineering (ACE)
    # e o uso do Model Context Protocol (MCP) estão transformando a forma como desenvolvedores interagem com LLMs no dia a dia.
    # Esqueça o prompt engineering tradicional: o futuro pertence ao contexto estruturado e dinâmico.
    # Boa leitura!
    # """,
    # """
    # Olá, tudo bem?

    # Gostaríamos de agradecer imensamente sua participação em nosso processo seletivo para a vaga de Especialista em Engenharia de Software.
    # Ficamos muito impressionados com seu background técnico e sua experiência com arquitetura distribuída.
    # No entanto, optamos por seguir com outro candidato que possuía maior alinhamento sênior com a stack específica do projeto atual.
    # Manteremos seu currículo em nosso banco de talentos.
    # """,
    # """
    # Prezado cliente,

    # O seu objeto postado em São Paulo/SP foi integrado ao nosso sistema de fluxo postal.

    # Código de rastreio: BR839102931BR
    # Status atual: Objeto encaminhado para a Unidade de Tratamento.
    # Prazo estimado de entrega: 4 dias úteis.

    # Para acompanhar as movimentações futuras, utilize o aplicativo dos Correios ou nosso site oficial.
    # """
]

In [4]:
import os
from google.colab import userdata

os.environ['GOOGLE_API_KEY'] = userdata.get('GEMINI_KEY')

In [5]:
from google import genai

client = genai.Client()

In [ ]:
def resumidor_de_emails(lista_de_emails):
  for i, email in enumerate(lista_de_emails):
    resposta = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=f""" Vou te mandar o corpo de um e-mail. Quero que você o resuma em apenas 1 linha,
        passando o intuito daquele e-mail.
        Segue o e-mail: {email}
        """
        )

    print(f"E-mail {i + 1}: {resposta.text}")
    print("-" * 50)

In [ ]:
resumidor_de_emails(emails)

E-mail 1: **Alerta de nova chave Pix cadastrada: verifique a ação ou contate-nos imediatamente se não a reconhece.**
--------------------------------------------------
E-mail 2: Convite para um churrasco de aniversário no sábado, a partir das 13h, onde o valor das carnes e bebidas será rachado via Pix, com pedido de confirmação até amanhã.
--------------------------------------------------
E-mail 3: Alerta CloudWatch: A CPU de um EC2 está em 94.2%, acima do limite, acionando a equipe de DevOps.
--------------------------------------------------
E-mail 4: Este e-mail divulga uma oportunidade urgente de lucro fácil e garantido pelo celular, sem precisar de experiência.
--------------------------------------------------
E-mail 5: Não perca o prazo final nesta sexta-feira, às 17h, para realizar alterações ou incluir dependentes no seu plano de saúde.
--------------------------------------------------

# LLMs

In [2]:
!pip install -q groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 4.1 MB/s eta 0:00:00

In [3]:
import os
from google.colab import userdata

os.environ['GROQ_KEY'] = userdata.get('GROQ_KEY')

In [ ]:
from groq import Groq

client = Groq(api_key=os.environ.get("GROQ_KEY"))
completion = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[
      {
        "role": "user",
        "content": "Falando sobre modelos de IA, o que difere um modelo de 8B para um de 20B?"
      }
    ],
    temperature=1, # - menos criativo possível | + mais criativo possível
    max_completion_tokens=1024,
    top_p=1,
    stream=True,
    stop=None
)

for chunk in completion:
    print(chunk.choices[0].delta.content or "", end="")

Existem várias diferenças entre um modelo de IA com 8 bilhões de parâmetros (8B) e um modelo com 20 bilhões de parâmetros (20B). Aqui estão algumas das principais diferenças:

1. **Capacidade de processamento de linguagem**: Modelos com mais parâmetros tendem a ter melhor capacidade de processar linguagem, incluindo a compreensão de expressões complexas, referências contextuais e ambiguidades. Um modelo de 20B pode ser capaz de capturar e entender melhor nuances da linguagem humana em comparação a um modelo de 8B.
2. **Desempenho em tarefas de linguagem**: Os modelos com mais parâmetros tendem a ter melhor desempenho em tarefas de linguagem como a classificação de texto, extração de informações, resumo de texto e geração de texto. Um modelo de 20B pode ser capaz de realizar essas tarefas com maior precisão e eficiência em comparação a um modelo de 8B.
3. **Capacidade de generalização**: Modelos com mais parâmetros tendem a ter melhor capacidade de generalização, o que significa que eles podem ser capazes de realizar bem em tarefas novas e inesperadas. Um modelo de 20B pode ser capaz de adaptar-se mais facilmente a novos dados e situações em comparação a um modelo de 8B.
4. **Complexidade computacional**: Modelos com mais parâmetros requerem mais recursos computacionais para treinar e executar. Um modelo de 20B pode precisar de mais recursos de hardware, como processadores mais rápidos e memória de computador maior, em comparação a um modelo de 8B.
5. **Custo de desenvolvimento**: Modelos com mais parâmetros frequentemente requerem mais tempo, dinheiro e esforço de desenvolvimento para criar e treinar. Um modelo de 20B pode ser mais caro e demorado para desenvolver em comparação a um modelo de 8B.
6. **Desenvolvimento de características**: Com mais parâmetros, os modelos podem aprender características mais complexas e sutis do dados, como relacionamentos entre diferentes variáveis, padrões de comportamento e tendências. Isso pode levar a descobertas inesperadas e insights novos em comparação a modelos com menos parâmetros.
7. **Robustez**: Os modelos com mais parâmetros tendem a ser mais robustos e menos propensos a erros de overfitting, em que o modelo é muito especializado em um conjunto de dados específico e não geraliza bem para outros conjuntos de dados.

É importante notar que a quantidade de parâmetros não é o único fator que determina a capacidade de um modelo de IA. Outros fatores, como a qualidade dos dados de treinamento, a escolha do algoritmo e a optimização do modelo, também têm um impacto significativo no desempenho do modelo.

## Lendo e escrevendo em arquivos python

In [6]:
def resumidor_de_emails(lista_de_emails):
  lista_de_resumos = []

  for i, email in enumerate(lista_de_emails):
    resposta = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=f""" Vou te mandar o corpo de um e-mail. Quero que você o resuma em apenas 1 linha,
          passando o intuito daquele e-mail.
          Segue o e-mail: {email}
          """
        )

    resumo = f"E-mail {i + 1}: {resposta.text}"
    print(resumo)
    lista_de_resumos.append(resumo)
    print("-" * 50)

  return lista_de_resumos

In [10]:
lista_resumos = resumidor_de_emails(emails)

E-mail 1: Sua conta teve uma nova chave Pix cadastrada; entre em contato imediatamente se você não reconhece essa operação.
--------------------------------------------------
E-mail 2: Convite para churrasco de aniversário no sábado com rachadinha de custos, pedindo confirmação de presença até amanhã.
--------------------------------------------------
E-mail 3: Um alarme do CloudWatch disparou por CPU de EC2 em 94.2% (acima de 90%), escalando para a equipe DevOps.
--------------------------------------------------
E-mail 4: O e-mail é um convite urgente para uma vaga de trabalho fácil e lucrativo pelo celular, sem experiência.
--------------------------------------------------
E-mail 5: Lembrete final: o prazo para alterações no plano de saúde (incluindo dependentes e acomodação) é nesta sexta-feira, às 17h.
--------------------------------------------------

In [12]:
with open("lista-de-resumos.txt", "w", encoding="utf-8") as arquivo:
  for resumo in lista_resumos:
    arquivo.write(resumo + "\n")

In [17]:
nova_lista_de_leitura = []

with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:
  for linha in arquivo:
    nova_lista_de_leitura.append(linha.strip())

In [18]:
nova_lista_de_leitura

['E-mail 1: Sua conta teve uma nova chave Pix cadastrada; entre em contato imediatamente se você não reconhece essa operação.',
 'E-mail 2: Convite para churrasco de aniversário no sábado com rachadinha de custos, pedindo confirmação de presença até amanhã.',
 'E-mail 3: Um alarme do CloudWatch disparou por CPU de EC2 em 94.2% (acima de 90%), escalando para a equipe DevOps.',
 'E-mail 4: O e-mail é um convite urgente para uma vaga de trabalho fácil e lucrativo pelo celular, sem experiência.',
 'E-mail 5: Lembrete final: o prazo para alterações no plano de saúde (incluindo dependentes e acomodação) é nesta sexta-feira, às 17h.']

In [23]:
conteudo = ""

with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:
  conteudo = arquivo.read() # Sem muito controle da formatação. ex: \n

In [20]:
conteudo

'E-mail 1: Sua conta teve uma nova chave Pix cadastrada; entre em contato imediatamente se você não reconhece essa operação.\nE-mail 2: Convite para churrasco de aniversário no sábado com rachadinha de custos, pedindo confirmação de presença até amanhã.\nE-mail 3: Um alarme do CloudWatch disparou por CPU de EC2 em 94.2% (acima de 90%), escalando para a equipe DevOps.\nE-mail 4: O e-mail é um convite urgente para uma vaga de trabalho fácil e lucrativo pelo celular, sem experiência.\nE-mail 5: Lembrete final: o prazo para alterações no plano de saúde (incluindo dependentes e acomodação) é nesta sexta-feira, às 17h.\n'

In [24]:
nova_lista_de_leitura_2 = []

with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:
  nova_lista_de_leitura_2 = arquivo.readlines() # Sem muito controle da formatação. ex: \n

In [22]:
nova_lista_de_leitura_2

['E-mail 1: Sua conta teve uma nova chave Pix cadastrada; entre em contato imediatamente se você não reconhece essa operação.\n',
 'E-mail 2: Convite para churrasco de aniversário no sábado com rachadinha de custos, pedindo confirmação de presença até amanhã.\n',
 'E-mail 3: Um alarme do CloudWatch disparou por CPU de EC2 em 94.2% (acima de 90%), escalando para a equipe DevOps.\n',
 'E-mail 4: O e-mail é um convite urgente para uma vaga de trabalho fácil e lucrativo pelo celular, sem experiência.\n',
 'E-mail 5: Lembrete final: o prazo para alterações no plano de saúde (incluindo dependentes e acomodação) é nesta sexta-feira, às 17h.\n']

## Manipulando dados com pandas

In [25]:
import pandas as pd

In [26]:
df = pd.read_csv("/content/meu_csv.csv")

In [27]:
df

                Nome  Média
0          Ana Silva    8.5
1       Bruno Santos    7.2
2    Carlos Oliveira    6.8
3       Daniela Lima    9.1
4      Eduardo Costa    5.4
5     Fernanda Souza    8.0
6    Gabriel Almeida    7.5
7    Juliana Ribeiro    6.2
8      Lucas Pereira    9.5
9  Mariana Rodrigues    4.9

In [28]:
df.head()

              Nome  Média
0        Ana Silva    8.5
1     Bruno Santos    7.2
2  Carlos Oliveira    6.8
3     Daniela Lima    9.1
4    Eduardo Costa    5.4

In [29]:
df.tail()

                Nome  Média
5     Fernanda Souza    8.0
6    Gabriel Almeida    7.5
7    Juliana Ribeiro    6.2
8      Lucas Pereira    9.5
9  Mariana Rodrigues    4.9

## Desafio:

  1. Cria um arquivo .txt a partir de uma lista de perguntas vindas de uma lista em Python [].
  2. Ler essas perguntas desse arquivo .txt e salva-las em uma lista Python.
  3. Obter respostas de um LLM para cada uma.
  4. Salvar os resultados em um novo arquivo .csv
  5. Ler o arquivo .csv usando o pandas

In [30]:
# Etapa 1
lista_de_perguntas = [
    "Qual é a capital da Austrália?",
    "Quem pintou a 'Mona Lisa'?",
    "Quantos planetas existem no Sistema Solar?",
    "Em que ano terminou a Segunda Guerra Mundial?",
    "Qual é o rio mais longo do mundo?",
    "Quem escreveu 'Dom Casmurro'?",
    "Qual elemento químico tem o símbolo 'O'?",
    "Qual é o animal terrestre mais rápido do mundo?",
    "Quantos ossos tem um corpo humano adulto?",
    "Em qual continente fica o Deserto do Saara?"
]

In [33]:
with open("lista-de-perguntas.txt", "w", encoding="utf-8") as arquivo:
  for pergunta in lista_de_perguntas:
    arquivo.write(pergunta + "\n")

In [36]:
# Etapa 2
nova_lista_perguntas = []

with open("lista-de-perguntas.txt", "r", encoding="utf-8") as arquivo:
  for i, linha in enumerate(arquivo):
    print(f"Pergunta: {i + 1} - {linha.strip()}")
    print("-" * 50)
    nova_lista_perguntas.append(linha.strip())

Pergunta: 1 - Qual é a capital da Austrália?
--------------------------------------------------
Pergunta: 2 - Quem pintou a 'Mona Lisa'?
--------------------------------------------------
Pergunta: 3 - Quantos planetas existem no Sistema Solar?
--------------------------------------------------
Pergunta: 4 - Em que ano terminou a Segunda Guerra Mundial?
--------------------------------------------------
Pergunta: 5 - Qual é o rio mais longo do mundo?
--------------------------------------------------
Pergunta: 6 - Quem escreveu 'Dom Casmurro'?
--------------------------------------------------
Pergunta: 7 - Qual elemento químico tem o símbolo 'O'?
--------------------------------------------------
Pergunta: 8 - Qual é o animal terrestre mais rápido do mundo?
--------------------------------------------------
Pergunta: 9 - Quantos ossos tem um corpo humano adulto?
--------------------------------------------------
Pergunta: 10 - Em qual continente fica o Deserto do Saara?
--------------------------------------------------

In [42]:
# Etapa 3
!pip install -q groq

In [43]:
import os
from google.colab import userdata

os.environ['GROQ_KEY'] = userdata.get('GROQ_KEY')

In [45]:
from groq import Groq

client = Groq(api_key=os.environ.get("GROQ_KEY"))

In [62]:
def tira_duvidas(lista_de_duvidas):
    lista_de_respostas = []

    for i, pergunta in enumerate(lista_de_duvidas):
        pergunta_formatada = f"""Responda a minha pergunta de forma resumida e no máximo de 1 linha.
        {pergunta}
        """

        completion = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {
                    "role": "user",
                    "content": pergunta_formatada
                }
            ],
            temperature=1,
            max_completion_tokens=1024,
            top_p=1,
            stream=True,
            stop=None
        )

        resposta_completa = ""
        print(f"Resposta {i + 1}: ", end="")

        for chunk in completion:
            texto_chunk = chunk.choices[0].delta.content or ""
            print(texto_chunk, end="")
            resposta_completa += texto_chunk

        print("\n")

        lista_de_respostas.append(resposta_completa)

    return lista_de_respostas

In [63]:
respostas = tira_duvidas(nova_lista_perguntas)

Resposta 1: Canberra é a capital da Austrália.

Resposta 2: O famoso quadro "Mona Lisa" foi pintado pelo artista italiano Leonardo da Vinci.

Resposta 3: Existem 8 planetas no Sistema Solar (Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano e Netuno), mas é importante notar que Plutão é considerado um planoeta anão desde 2006.

Resposta 4: A Segunda Guerra Mundial terminou em 1945.

Resposta 5: O rio mais longo do mundo é o Rio Amazonas, com cerca de 6.800 km de extensão.

Resposta 6: "Dom Casmurro" foi escrito pelo escritor brasileiro Machado de Assis.

Resposta 7: O elemento químico que tem o símbolo "O" é o Oxigênio.

Resposta 8: O cágado é considerado o mais rápido, podendo alcançar até 70 km/h.

Resposta 9: Um corpo humano adulto tem 206 ossos.

Resposta 10: O Deserto do Saara localiza-se na África.

In [64]:
respostas

['Canberra é a capital da Austrália.',
 'O famoso quadro "Mona Lisa" foi pintado pelo artista italiano Leonardo da Vinci.',
 'Existem 8 planetas no Sistema Solar (Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano e Netuno), mas é importante notar que Plutão é considerado um planoeta anão desde 2006.',
 'A Segunda Guerra Mundial terminou em 1945.',
 'O rio mais longo do mundo é o Rio Amazonas, com cerca de 6.800 km de extensão.',
 '"Dom Casmurro" foi escrito pelo escritor brasileiro Machado de Assis.',
 'O elemento químico que tem o símbolo "O" é o Oxigênio.',
 'O cágado é considerado o mais rápido, podendo alcançar até 70 km/h.',
 'Um corpo humano adulto tem 206 ossos.',
 'O Deserto do Saara localiza-se na África.']

In [71]:
# Etapa 4
import csv

In [78]:
with open("lista-de-respostas.csv", mode="w", newline="", encoding="utf-8") as arquivo:
  escritor = csv.writer(arquivo)
  escritor.writerow(["Respostas"])

  for i, resposta in enumerate(respostas):
    escritor.writerow([resposta])

In [79]:
# Etapa 5
import pandas as pd

In [80]:
pd.read_csv("/content/lista-de-respostas.csv")

                                           Respostas
0                 Canberra é a capital da Austrália.
1  O famoso quadro "Mona Lisa" foi pintado pelo a...
2  Existem 8 planetas no Sistema Solar (Mercúrio,...
3         A Segunda Guerra Mundial terminou em 1945.
4  O rio mais longo do mundo é o Rio Amazonas, co...
5  "Dom Casmurro" foi escrito pelo escritor brasi...
6  O elemento químico que tem o símbolo "O" é o O...
7  O cágado é considerado o mais rápido, podendo ...
8              Um corpo humano adulto tem 206 ossos.
9          O Deserto do Saara localiza-se na África.

## Solução do Professor

In [83]:
# Etapa 1
lista_de_perguntas = [
    "Qual é a capital da Austrália?",
    "Quem pintou a 'Mona Lisa'?",
    "Quantos planetas existem no Sistema Solar?",
    "Em que ano terminou a Segunda Guerra Mundial?",
    "Qual é o rio mais longo do mundo?",
    "Quem escreveu 'Dom Casmurro'?",
    "Qual elemento químico tem o símbolo 'O'?",
    "Qual é o animal terrestre mais rápido do mundo?",
    "Quantos ossos tem um corpo humano adulto?",
    "Em qual continente fica o Deserto do Saara?"
]

with open("lista-de-perguntas-professor.txt", "w", encoding="utf-8") as arquivo:
  for pergunta in lista_de_perguntas:
    arquivo.write(pergunta + "\n")

In [85]:
# Etapa 2
lista_desafio = []

with open("lista-de-perguntas-professor.txt", "r", encoding="utf-8") as arquivo:
  for linha in arquivo:
    lista_desafio.append(linha.strip())

print(lista_desafio)

['Qual é a capital da Austrália?', "Quem pintou a 'Mona Lisa'?", 'Quantos planetas existem no Sistema Solar?', 'Em que ano terminou a Segunda Guerra Mundial?', 'Qual é o rio mais longo do mundo?', "Quem escreveu 'Dom Casmurro'?", "Qual elemento químico tem o símbolo 'O'?", 'Qual é o animal terrestre mais rápido do mundo?', 'Quantos ossos tem um corpo humano adulto?', 'Em qual continente fica o Deserto do Saara?']

In [88]:
# Etapa 3
def busca_respostas(lista_desafio):
    lista_de_dicionarios = []

    for pergunta in lista_desafio:
        pergunta_formatada = f"""Gere uma resposta muito sucinta e em 1 linha sobre a minha pergunta.
        {pergunta}
        """

        completion = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {
                    "role": "user",
                    "content": pergunta_formatada
                }
            ],
            temperature=1,
            max_completion_tokens=1024,
            top_p=1,
            stream=True,
            stop=None
        )

        resposta_completa = ""
        for chunk in completion:
            texto_chunk = chunk.choices[0].delta.content or ""
            resposta_completa += texto_chunk

        resposta = {"pergunta": pergunta, "resposta": resposta_completa}
        lista_de_dicionarios.append(resposta)

    return lista_de_dicionarios

In [89]:
lista_respostas_professor = busca_respostas(lista_desafio=lista_desafio)

In [90]:
print(lista_respostas_professor)

[{'pergunta': 'Qual é a capital da Austrália?', 'resposta': 'A capital da Austrália é Canberra.'}, {'pergunta': "Quem pintou a 'Mona Lisa'?", 'resposta': "Leonardo da Vinci pintou a 'Mona Lisa'."}, {'pergunta': 'Quantos planetas existem no Sistema Solar?', 'resposta': 'Existem 8 planetas no Sistema Solar: Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano e Netuno.'}, {'pergunta': 'Em que ano terminou a Segunda Guerra Mundial?', 'resposta': 'A Segunda Guerra Mundial terminou oficialmente em 2 de setembro de 1945.'}, {'pergunta': 'Qual é o rio mais longo do mundo?', 'resposta': 'O rio mais longo do mundo é o Rio Nilo, com aproximadamente 6.695 km, localizado principalmente na África.'}, {'pergunta': "Quem escreveu 'Dom Casmurro'?", 'resposta': '"Dom Casmurro" foi escrito por Machado de Assis.'}, {'pergunta': "Qual elemento químico tem o símbolo 'O'?", 'resposta': "O elemento químico com símbolo 'O' é Oxiônio é incorrecto, a pergunta pede o símbolo 'O' sem a numeração, e não foi mencionado, então o elemento químico pedido é o Oxi e não era a resposta. A resposta correta em português para a pergunta seria o óxido não é  ocorrência. O elemento químico com símbolo 'O' é oxigênio."}, {'pergunta': 'Qual é o animal terrestre mais rápido do mundo?', 'resposta': 'O animal terrestre mais rápido do mundo é a guepardo, alcançando velocidades de até 120 km/h.'}, {'pergunta': 'Quantos ossos tem um corpo humano adulto?', 'resposta': 'Um corpo humano adulto tem cerca de 206 ossos.'}, {'pergunta': 'Em qual continente fica o Deserto do Saara?', 'resposta': 'O Deserto do Saara está localizado na África.'}]

In [91]:
# Etapa 4
with open("lista-de-respostas-professor.csv", mode="w", encoding="utf-8") as arquivo:
  arquivo.write("pergunta,resposta\n")

  for pergunta_dict in lista_respostas_professor:
    arquivo.write(f"{pergunta_dict['pergunta']},{pergunta_dict['resposta']}\n")

In [94]:
# Etapa 4 usando pandas
df_perguntas_respostas = pd.DataFrame(lista_respostas_professor)

df_perguntas_respostas.to_csv("lista-de-respostas-professor-pandas.csv", index=False, encoding="utf-8")

In [95]:
# Etapa 5

df_perguntas_respostas = pd.read_csv("lista-de-respostas-professor-pandas.csv")

In [97]:
df_perguntas_respostas.head()

,pergunta,resposta
0,Qual é a capital da Austrália?,A capital da Austrália é Canberra.
1,Quem pintou a 'Mona Lisa'?,Leonardo da Vinci pintou a 'Mona Lisa'.
2,Quantos planetas existem no Sistema Solar?,"Existem 8 planetas no Sistema Solar: Mercúrio,..."
3,Em que ano terminou a Segunda Guerra Mundial?,A Segunda Guerra Mundial terminou oficialmente...
4,Qual é o rio mais longo do mundo?,"O rio mais longo do mundo é o Rio Nilo, com ap..."